const styles = (theme) => {
  return ({
    container: {
      display: "flex",
      flexDirection: "column",
      backgroundColor: theme.backgroundPrimary,
      height: "100vh",
      width: "100vw",
    },
    wrapper: {
      display: "flex",
      flexDirection: "column",
      backgroundColor: theme.backgroundPrimary,
      overflow: "auto",
      height: "100vh",
      paddingTop: 60,
      paddingInline: 20,
    },
    setList: {
      display: "flex",
      flexDirection: "column",
      paddingTop: 10,
    },
    inputLabel: {
      color: theme.text,
      fontSize: 16,
      paddingTop: 6,
    },
    weightText: {
      color: theme.textHighlight,
      fontSize: 20,
      fontWeight: "bold",
    },

    input: {
      backgroundColor: theme.backgroundSecondary,
      height: 50,
      // width: "100%",
      minWidth: "45%",
      borderColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderRadius: 12,
      marginTop: 6,
      marginBottom: 6,
      padding: 10,
      paddingLeft: 22,
      color: theme.text,
      fontSize: 20,
      fontWeight: "bold",
    },
    inputDynamicHeight: {
      backgroundColor: theme.backgroundSecondary,
      height: 50,
      // width: "100%",
      minWidth: "45%",
      borderColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderRadius: 12,
      marginTop: 6,
      marginBottom: 6,
      padding: 10,
      paddingLeft: 22,
      color: theme.text,
      fontSize: 20,
      fontWeight: "bold",
    },
    inputExerciseVariationName: {
      backgroundColor: theme.backgroundSecondary,
      height: 50,
      width: "80%",
      borderColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderRadius: 12,
      marginTop: 6,
      marginBottom: 6,
      padding: 10,
      paddingLeft: 22,
      color: theme.text,
      fontSize: 20,
      fontWeight: "bold",
    },

    exerciseItem: {
      display: "flex",
      flexDirection: "column",
      paddingBottom: 20,
      marginBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.textFaded,
    },
    exerciseItemRemoveIconContainer: {
      width: 25,
      height: 25,
      marginLeft: "auto",
      cursor: "pointer",
    },
    exerciseItemRemoveIcon: {
      color: theme.text,
      fill: theme.text,
    },
    row: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    col: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
    },
    colWeight: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      minWidth: "45%",
    },

    AddExerciseButton: {
      backgroundColor: theme.active,
      borderRadius: 10,
      marginTop: 12,
      marginBottom: 12,
      // marginInline: 20,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      cursor: "pointer",
      height: 36,
    },
    AddExerciseButtonText: {
      color: theme.text,
      fontSize: 16,
      fontWeight: "bold",
      textAlign: "center",
    },
  });
}

export default styles;
