const styles = (theme) => {
  return ({
    container: {
      display: "flex",
      flexDirection: "column",
      backgroundColor: theme.backgroundPrimary,
      height: "100vh",
      width: "100vw",
      whiteSpace: "nowrap",
    },
    wrapper: {
      display: "flex",
      flexDirection: "column",
      backgroundColor: theme.backgroundPrimary,
      // height: "100vh",
      overflow: "auto",
      paddingLeft: 60,
      paddingBottom: 70,
      paddingTop: 44,
    },
    cardWarning: {
      backgroundColor: theme.textHighlight,
      padding: 16,
      marginTop: 20,
      marginInline: 20,
      borderRadius: 10,
      height: 130,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      whiteSpace: "break-spaces",

    },
    textWarning: {
      color: theme.backgroundPrimary,
      fontSize: 20,
      fontWeight: "bold",
      textAlign: "center",
    },

    cardIncrement: {
      backgroundColor: theme.backgroundSecondary,
      padding: 22,
      marginTop: 20,
      marginInline: 20,
      borderRadius: 10,
      height: 240,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "space-between",
    },
    title: {
      color: theme.text,
      fontSize: 12,
    },
    rowWrapper: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
    },
    row: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "80%",
    },
    incrementWrapper: {
      minWidth: 50,
      minHeight: 50,
      backgroundColor: theme.backgroundSecondary,
      border: `2px solid ${theme.active}`,
      borderRadius: "50%",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      cursor: "pointer",
      userSelect: "none",
    },
    incrementText: {
      color: theme.text,
      fontSize: 16,
    },
    repsSets: {
      color: theme.text,
      fontSize: 24,
      margin: 20,
    },

    card1RM: {
      backgroundColor: theme.backgroundSecondary,
      padding: 22,
      marginTop: 20,
      marginInline: 20,
      borderRadius: 10,
      // height: 430,
      height: "auto",
      flex: 0,
    },
    cardPercentage: {
      backgroundColor: theme.backgroundSecondary,
      padding: 22,
      marginInline: 20,
      marginTop: 20,
      marginBottom: 20,
      borderRadius: 10,
      // height: 430,
      height: "auto",
      flex: 0,
    },
    title1RM: {
      color: theme.textHighlight,
      fontSize: 16,
      fontWeight: "bold",
    },
    card1RMRow1: {
      display: "flex",
      flexDirection: "row",
      width: "100%",
      justifyContent: "space-around",
      marginTop: 20,
      paddingBottom: 16,
      borderBottom: `1px solid ${theme.textFaded}`,
    },
    card1RMRow2: {
      display: "flex",
      flexDirection: "row",
      width: "100%",
      justifyContent: "space-around",
      marginTop: 16,
    },
    card1RMCol: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    weightTop: {
      fontSize: 28,
      fontWeight: "bold",
      marginBottom: 6,
      color: theme.text,
    },
    card1RMColContentRow: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 14,
    },
    weightBottom: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme.text,
    },
    weightSubTop: {
      color: theme.text,
    },
    weightSubBottom: {
      marginRight: 10,
      color: theme.text,
    },
    modalContent: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
  });
}

export default styles;
