const styles = (theme) => {
  return ({
    container: {
      // backgroundColor: "red",
      position: "absolute", // absolute
      top: 50,
      marginLeft: 60,
      width: "100%",
      maxHeight: 53,
      // display: "flex",
      // flexDirection: "row",
      marginBottom: 10,
      // marginTop: 50,
      // marginLeft: 60,
      overflowY: "hidden",
      overflowX: "auto",
    },
    wrapper: {
      // backgroundColor: "red",
      position: "relative",
      // top: 50,
      // left: 60,
      // width: "100%",
      // maxHeight: 53,
      display: "flex",
      flexDirection: "row",
      // marginBottom: 10,
      // marginTop: 50,
      // marginLeft: 60,
      // overflowY: "hidden",
      // overflowX: "auto",
    },
    tabItem: {
      backgroundColor: theme.backgroundSecondary,
      height: 50,
      minWidth: 80,
      flex: 1,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      borderBottom: `3px solid ${theme.backgroundSecondary}`,
      cursor: "pointer",
    },
    tabItemSelected: {
      backgroundColor: theme.backgroundSecondary,
      height: 50,
      minWidth: 80,
      flex: 1,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      borderBottom: `3px solid ${theme.textHighlight}`,
      cursor: "pointer",
    },
    text: {
      color: theme.text,
      fontSize: 18,
      lineHeight: 30,
      fontWeight: "bold",
      textTransform: "capitalize",
    },
    textSelected: {
      color: theme.textHighlight,
      fontSize: 18,
      lineHeight: 30,
      fontWeight: "bold",
      textTransform: "capitalize",
    },
  });
}

export default styles;
